WIDTH, HEIGHT = 1200, 700
FRAME_RATE_PER_SECOND = 30
DIALOG_WIDTH, DIALOG_HEIGHT = (400, 300)
IMAGES_PATH = "assets/images/"
BOARD_SIZE = (10, 10)
BOARD_SIZE_WIDTH = BOARD_SIZE[0]
BOARD_SIZE_HEIGHT = BOARD_SIZE[1]
